# Site settings
title: island
email: 1114396764@qq.com
baseurl: "/weakgrow" # the subpath of your site, e.g. /blog
#url: "http://zhaohuashop.com" # the base hostname & protocol for your site

# Sidebar settings
description: 灵魂和身体都需要奔跑

gems: [jekyll-paginate]

paginate: 5
paginate_path: "blog/page:num"

#pagin
paginate: 5
# Social icons
facebook: daisyHawen
linkedin: daisyHawen
github: daisyHawen
deviantart: username
codepen: username

footer: © DaisyHawen


# Build settings
markdown: kramdown
